### ISSUE TITLE
interactWriteDryRun should work with interactWrite

### ISSUE THREAD

**Issue by TheLoneRonin** [ArweaveTeam/SmartWeave#44]
Currently `interactWrite` will write the transaction even if the input might be faulty. Furthermore, `interactWrite` only displays the transaction id after submitting.

It would be great if there was the following:

1. Instead of returning only a tx id. Return a tx id plus the contract result as seen here: https://github.com/ArweaveTeam/SmartWeave/blob/master/SDK.md#interactwritedryrun

2. If the dry run returns an error. Throw an error instead of writing the bad input.

3. This is configurable via an opts parameter something like `outputResult: boolean`. Therefore updating `interactWrite` to:

```
async function interactWrite(arweave: Arweave, wallet: JWKInterface, contractId: string, input: any, opts: Object): Promise<ContractInteractionResult | string>
```

**Comment by t8** [comment]
Personally a big fan of this proposal. That would be so useful.

(Coming from someone who has a reputation of accidentally publishing over 1000 invalid contract interactions)

**Comment by TheLoneRonin** [comment]
@t8 after discussing with Sam about the potential problems from replaying every tx locally. This implementation can be problematic on a local machine that might not want to load the entire transaction history.

I think the most we can do to prevent a bad tx from submitting (other than validating inputs manually) is only estimate the network fee for submitting a tx. Either way, what Sam mentioned in regards to potential problems re: RAM and CPU to replay txs makes this proposal not good at scale.

I'll have to come back to this problem later as there may be a workaround to this. I do think there is a resolution if we have some sort of `interactRead` to verify the latest state... But, the above is not viable.

**Comment by t8** [comment]
This makes a lot of sense. I hadn't considered the implications of integrating the feature. Thanks for explaining!
